POST http://localhost:4000/product
Content-Type: application/json

{
    "product_Name": "Bag",
    "product_Description": "Handbag",
    "product_Price": 4500
}

#### a product
GET http://localhost:4000/product/


####products
GET http://localhost:4000/products


####search product
POST http://localhost:4000/product/search?q=Shoes


####paginate products
POST http://localhost:4000/product/paginate 
Content-Type: application/json

{
     "page": 1,
    "size": 5
}





